[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fuzz]
runs = 10

[profile.ci.fuzz]
runs = 256

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
