name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create Claude credentials file
        env:
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
        run: |
          mkdir -p ~/.claude
          printf '%s' "$CREDENTIALS_JSON" > ~/.claude/.credentials.json
          echo "::notice::Credentials file created at ~/.claude/.credentials.json"

      - name: Run Claude Code
        id: claude
        env:
          CLAUDE_CODE_ACTION: ""
        # Using forked action without API key validation
        uses: dnakov/claude-code-action@841a525627187f2b98aea2688c57f627cb4a0548